train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 8
      augment: true
      sample_q: 2048
      pad_mode: reflect
  augmenter:
    name: compose
    args:
      - name: h_flip
        args: {}
      - name: v_flip
        args: {}
      - name: rot
        args: {}
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2048
  batch_size: 16

data_norm:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]

model:
  name: liif-base
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    predictor_spec:
      name: lte
      args:
        num_pred: 64
        out_dim: 3
    decoder_spec:
      name: accumulator
      args:
        out_dim: 3

loss:
  name: compose
  args:
  - name: l1
    weight: 1.0
    args:
      pred_key: recon
      target_key: gt_rgb

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 400
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

amp: False
resume: ./save/_lte/epoch-last.pth
SEED: 123