train_dataset:
  dataset:
    name: image-folder-gray
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      repeat: 1
      first_k: 20
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      # patch_crop: 48
      sample_q: 128
  augmenter:
    name: compose
    args:
      - name: h_flip
        args: {}
      - name: v_flip
        args: {}
      - name: rot
        args: {}
  batch_size: 1

val_dataset:
  dataset:
    name: image-folder-gray
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 2
      repeat: 1
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      # patch_crop: 48
      sample_q: 128
  batch_size: 2

data_norm:
  mean: [0.5]
  std: [0.5]
clip_grad: 100.0

model:
  name: liif-base
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    predictor_spec:
      name: recurrent-lte
      args:
        num_pred: 128
        out_dim: 3
        block_size: 4
        rnn_spec:
          name: recurrent-transformer
          args:
            pos_encoding: 'stochastic-position-encoding'
    decoder_spec:
      name: accumulator
      args:
        out_dim: 3
        scaling: False

loss:
  name: compose
  args:
  - name: l1
    weight: 1.0
    args:
      pred_key: recon
      target_key: gt_rgb
  - name: partial-l1
    weight: 0.01
    args:
      mode: random

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

amp: False
SEED: 123
# test_dataset:
#   dataset:
#     name: image-folder
#     args:
#       root_path: ./load/div2k/DIV2K_valid_HR_mini
#   wrapper:
#     name: sr-implicit-downsampled
#     args:
#       scale_min: 18
#   batch_size: 1
# eval_type: div2k-4
# eval_bsize: 30000


# data_norm:
#   inp: {sub: [0.5], div: [0.5]}
#   gt: {sub: [0.5], div: [0.5]}